### ISSUE TITLE
Abilities and runemark for Dwarfs

### ISSUE THREAD

**Issue by Dreadaxe** [markblokpoel/battlescribe-custom-warcry-export#9] opened 2021-10-24 21:31 UTC
![image](https://user-images.githubusercontent.com/13752505/138613698-aa68f806-4baa-4736-9c6d-8f11f30fd4e2.png)

**Comment by markblokpoel** [comment] 2021-10-25 07:23
It seems that this is a problem with the data, the abilities also do not show up in the default battlescribe overview. Will pass this on to the warcry dataset team. I know they've been redesigning the CoS data a few times now, since they do not fit the default data format. Closing the issue here.

**Closed as completed by markblokpoel** 2021-10-25 07:23 UTC

**Comment by markblokpoel** [comment] 2021-10-25 08:20
Additional info: You need to add 'Select a City' to your roster and select the appropriate city for the correct runemarks to be linked to your units. You can always check if abilities are listed in the default BS overview. If not, then the problem is not on the card script.
